name: pnAutoMine
version: "${version}"
main: ru.privatenull.pnautomine.PnAutoMinePlugin
api-version: "1.21"
authors: [privatenull]
description: pnAutoMine - automatic mine reset plugin with WorldEdit integration
depend: [WorldEdit, pnLibrary]
softdepend: [FancyHolograms, DecentHolograms, PlaceholderAPI, TAB]
commands:
  pnautomine:
    description: pnAutoMine main command
    aliases: [mine, mines, am]
    usage: /pnautomine help
    permission: pnautomine.admin
permissions:
  pnautomine.admin:
    default: op
  pnautomine.use:
    default: true
